export const mockMapData = [
  {
    id: 0,
    level: "county",
    name: "Albany",
    stateAbbrev: "NY",
    lat: 42.6526,
    long: -73.7562,
    covidSummary: {
      preCovidCount: 65,
      postCovidCount: 24,
    },
    symptomsSummary: {
      preSymptomaticCount: 54,
      postSymptomaticCount: 23,
    },
    vaccinationSummary: {
      vaccinationCount: 34,
      boosterCount: 23,
      pfizerCount: 21,
      modernaCount: 54,
      jjCount: 39,
    },
    totalEntries: 25,
  },
  {
    id: 1,
    level: "county",
    name: "Allegany",
    stateAbbrev: "NY",
    lat: 42.313,
    long: -78.0195,
    covidSummary: {
      preCovidCount: 65,
      postCovidCount: 24,
    },
    symptomsSummary: {
      preSymptomaticCount: 54,
      postSymptomaticCount: 23,
    },
    vaccinationSummary: {
      vaccinationCount: 34,
      boosterCount: 23,
      pfizerCount: 21,
      modernaCount: 54,
      jjCount: 39,
    },
    totalEntries: 35,
  },
  {
    id: 2,
    level: "county",
    name: "Bronx",
    stateAbbrev: "NY",
    lat: 40.8448,
    long: -73.8648,
    covidSummary: {
      preCovidCount: 65,
      postCovidCount: 24,
    },
    symptomsSummary: {
      preSymptomaticCount: 54,
      postSymptomaticCount: 23,
    },
    vaccinationSummary: {
      vaccinationCount: 34,
      boosterCount: 23,
      pfizerCount: 21,
      modernaCount: 54,
      jjCount: 39,
    },
    totalEntries: 35,
  },
  {
    id: 3,
    level: "county",
    name: "Broome",
    stateAbbrev: "NY",
    lat: 42.1792,
    long: 75.8534,
    covidSummary: {
      preCovidCount: 65,
      postCovidCount: 24,
    },
    symptomsSummary: {
      preSymptomaticCount: 54,
      postSymptomaticCount: 23,
    },
    vaccinationSummary: {
      vaccinationCount: 34,
      boosterCount: 23,
      pfizerCount: 21,
      modernaCount: 54,
      jjCount: 39,
    },
    totalEntries: 35,
  },
  {
    id: 4,
    level: "county",
    name: "Cattaraugus",
    stateAbbrev: "NY",
    lat: 42.2318,
    long: -78.7476,
    covidSummary: {
      preCovidCount: 65,
      postCovidCount: 24,
    },
    symptomsSummary: {
      preSymptomaticCount: 54,
      postSymptomaticCount: 23,
    },
    vaccinationSummary: {
      vaccinationCount: 34,
      boosterCount: 23,
      pfizerCount: 21,
      modernaCount: 54,
      jjCount: 39,
    },
    totalEntries: 35,
  },
  {
    id: 5,
    level: "county",
    name: "Cayuga",
    stateAbbrev: "NY",
    lat: 42.7656,
    long: -76.5488,
    covidSummary: {
      preCovidCount: 65,
      postCovidCount: 24,
    },
    symptomsSummary: {
      preSymptomaticCount: 54,
      postSymptomaticCount: 23,
    },
    vaccinationSummary: {
      vaccinationCount: 34,
      boosterCount: 23,
      pfizerCount: 21,
      modernaCount: 54,
      jjCount: 39,
    },
    totalEntries: 35,
  },
  {
    id: 6,
    level: "county",
    name: "Chautauqua",
    stateAbbrev: "NY",
    lat: 42.2313,
    long: -79.5603,
    covidSummary: {
      preCovidCount: 65,
      postCovidCount: 24,
    },
    symptomsSummary: {
      preSymptomaticCount: 54,
      postSymptomaticCount: 23,
    },
    vaccinationSummary: {
      vaccinationCount: 34,
      boosterCount: 23,
      pfizerCount: 21,
      modernaCount: 54,
      jjCount: 39,
    },
    totalEntries: 35,
  },
  {
    id: 7,
    level: "county",
    name: "Chemung",
    stateAbbrev: "NY",
    lat: 42.1362,
    long: -76.78,
    covidSummary: {
      preCovidCount: 65,
      postCovidCount: 24,
    },
    symptomsSummary: {
      preSymptomaticCount: 54,
      postSymptomaticCount: 23,
    },
    vaccinationSummary: {
      vaccinationCount: 34,
      boosterCount: 23,
      pfizerCount: 21,
      modernaCount: 54,
      jjCount: 39,
    },
    totalEntries: 35,
  },
];
