/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateMapData = /* GraphQL */ `
  subscription OnCreateMapData {
    onCreateMapData {
      id
      level
      name
      stateAbbrev
      lat
      long
      covidSummary {
        covidCount
        percentHospitalizedDueToCovid
        avgPositiveCasesPerPerson
        percentSymptomatic
        percentTookMedication
        medicationCounts
        percentRecovered
      }
      symptomSummary {
        mostCommonSymptom
        symptomCounts
      }
      vaccinationSummary {
        percentVaccinated
        avgNumOfVaccPerPerson
        pfizerCount
        modernaCount
        jjCount
        azCount
      }
      generealHealthSummary {
        avgTotalScore
        avgHealthCounts
      }
      recoverySummary {
        longCovidCount
        percentLongCovid
        avgRecoveryLength {
          months
          days
        }
      }
      socialSummary {
        percentHaveMedicalInsurance
        percentDifficultyCoveringExpenses
        averageWorkingSituation
        workingSituationCounts
      }
      totalFullEntries
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateMapData = /* GraphQL */ `
  subscription OnUpdateMapData {
    onUpdateMapData {
      id
      level
      name
      stateAbbrev
      lat
      long
      covidSummary {
        covidCount
        percentHospitalizedDueToCovid
        avgPositiveCasesPerPerson
        percentSymptomatic
        percentTookMedication
        medicationCounts
        percentRecovered
      }
      symptomSummary {
        mostCommonSymptom
        symptomCounts
      }
      vaccinationSummary {
        percentVaccinated
        avgNumOfVaccPerPerson
        pfizerCount
        modernaCount
        jjCount
        azCount
      }
      generealHealthSummary {
        avgTotalScore
        avgHealthCounts
      }
      recoverySummary {
        longCovidCount
        percentLongCovid
        avgRecoveryLength {
          months
          days
        }
      }
      socialSummary {
        percentHaveMedicalInsurance
        percentDifficultyCoveringExpenses
        averageWorkingSituation
        workingSituationCounts
      }
      totalFullEntries
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteMapData = /* GraphQL */ `
  subscription OnDeleteMapData {
    onDeleteMapData {
      id
      level
      name
      stateAbbrev
      lat
      long
      covidSummary {
        covidCount
        percentHospitalizedDueToCovid
        avgPositiveCasesPerPerson
        percentSymptomatic
        percentTookMedication
        medicationCounts
        percentRecovered
      }
      symptomSummary {
        mostCommonSymptom
        symptomCounts
      }
      vaccinationSummary {
        percentVaccinated
        avgNumOfVaccPerPerson
        pfizerCount
        modernaCount
        jjCount
        azCount
      }
      generealHealthSummary {
        avgTotalScore
        avgHealthCounts
      }
      recoverySummary {
        longCovidCount
        percentLongCovid
        avgRecoveryLength {
          months
          days
        }
      }
      socialSummary {
        percentHaveMedicalInsurance
        percentDifficultyCoveringExpenses
        averageWorkingSituation
        workingSituationCounts
      }
      totalFullEntries
      createdAt
      updatedAt
    }
  }
`;
export const onCreateUser = /* GraphQL */ `
  subscription OnCreateUser($owner: String) {
    onCreateUser(owner: $owner) {
      id
      email
      age
      race
      lastSubmission
      lastSignIn
      notificationFreq
      notificaitonMethod
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateUser = /* GraphQL */ `
  subscription OnUpdateUser($owner: String) {
    onUpdateUser(owner: $owner) {
      id
      email
      age
      race
      lastSubmission
      lastSignIn
      notificationFreq
      notificaitonMethod
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteUser = /* GraphQL */ `
  subscription OnDeleteUser($owner: String) {
    onDeleteUser(owner: $owner) {
      id
      email
      age
      race
      lastSubmission
      lastSignIn
      notificationFreq
      notificaitonMethod
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onCreateSurveyEntry = /* GraphQL */ `
  subscription OnCreateSurveyEntry {
    onCreateSurveyEntry {
      id
      email
      createdAt
      surveyVersion
      surveyType
      age
      race
      timeElapsed
      covidEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        timesPositive
        lastPositive
        tested
        testMethod
        hospitalized
        symptomatic
        symptomsPreventScale
        medicationsTaken
        returnedToHealth
        createdAt
        updatedAt
        covidEntrySurveyEntryId
      }
      vaccinationEntry {
        id
        state
        countyState
        age
        race
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        totalVaccineShots
        vaccinated
        vaccineType
        dateOfLastVaccine
        createdAt
        updatedAt
        vaccinationEntrySurveyEntryId
      }
      socialDeterminantsEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        hasMedicalInsurance
        difficultCoveringExpenses
        currentWorkSituation
        createdAt
        updatedAt
        socialDeterminantsEntrySurveyEntryId
      }
      recoveryEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        recovered
        lengthOfRecovery {
          months
          days
        }
        hasLongCovid
        createdAt
        updatedAt
        recoveryEntrySurveyEntryId
      }
      generalHealthEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        health
        generalHealthResults
        totalScore
        createdAt
        updatedAt
        generalHealthEntrySurveyEntryId
      }
      symptomsEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        createdAt
        symptoms
        medicalConditions
        updatedAt
        symptomEntrySurveyEntryId
      }
      monthlyEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        results
        createdAt
        updatedAt
        monthlyEntrySurveyEntryId
      }
      updatedAt
      surveyEntryCovidEntryId
      surveyEntryVaccinationEntryId
      surveyEntrySocialDeterminantsEntryId
      surveyEntryRecoveryEntryId
      surveyEntryGeneralHealthEntryId
      surveyEntrySymptomsEntryId
      surveyEntryMonthlyEntryId
    }
  }
`;
export const onUpdateSurveyEntry = /* GraphQL */ `
  subscription OnUpdateSurveyEntry {
    onUpdateSurveyEntry {
      id
      email
      createdAt
      surveyVersion
      surveyType
      age
      race
      timeElapsed
      covidEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        timesPositive
        lastPositive
        tested
        testMethod
        hospitalized
        symptomatic
        symptomsPreventScale
        medicationsTaken
        returnedToHealth
        createdAt
        updatedAt
        covidEntrySurveyEntryId
      }
      vaccinationEntry {
        id
        state
        countyState
        age
        race
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        totalVaccineShots
        vaccinated
        vaccineType
        dateOfLastVaccine
        createdAt
        updatedAt
        vaccinationEntrySurveyEntryId
      }
      socialDeterminantsEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        hasMedicalInsurance
        difficultCoveringExpenses
        currentWorkSituation
        createdAt
        updatedAt
        socialDeterminantsEntrySurveyEntryId
      }
      recoveryEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        recovered
        lengthOfRecovery {
          months
          days
        }
        hasLongCovid
        createdAt
        updatedAt
        recoveryEntrySurveyEntryId
      }
      generalHealthEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        health
        generalHealthResults
        totalScore
        createdAt
        updatedAt
        generalHealthEntrySurveyEntryId
      }
      symptomsEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        createdAt
        symptoms
        medicalConditions
        updatedAt
        symptomEntrySurveyEntryId
      }
      monthlyEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        results
        createdAt
        updatedAt
        monthlyEntrySurveyEntryId
      }
      updatedAt
      surveyEntryCovidEntryId
      surveyEntryVaccinationEntryId
      surveyEntrySocialDeterminantsEntryId
      surveyEntryRecoveryEntryId
      surveyEntryGeneralHealthEntryId
      surveyEntrySymptomsEntryId
      surveyEntryMonthlyEntryId
    }
  }
`;
export const onDeleteSurveyEntry = /* GraphQL */ `
  subscription OnDeleteSurveyEntry {
    onDeleteSurveyEntry {
      id
      email
      createdAt
      surveyVersion
      surveyType
      age
      race
      timeElapsed
      covidEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        timesPositive
        lastPositive
        tested
        testMethod
        hospitalized
        symptomatic
        symptomsPreventScale
        medicationsTaken
        returnedToHealth
        createdAt
        updatedAt
        covidEntrySurveyEntryId
      }
      vaccinationEntry {
        id
        state
        countyState
        age
        race
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        totalVaccineShots
        vaccinated
        vaccineType
        dateOfLastVaccine
        createdAt
        updatedAt
        vaccinationEntrySurveyEntryId
      }
      socialDeterminantsEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        hasMedicalInsurance
        difficultCoveringExpenses
        currentWorkSituation
        createdAt
        updatedAt
        socialDeterminantsEntrySurveyEntryId
      }
      recoveryEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        recovered
        lengthOfRecovery {
          months
          days
        }
        hasLongCovid
        createdAt
        updatedAt
        recoveryEntrySurveyEntryId
      }
      generalHealthEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        health
        generalHealthResults
        totalScore
        createdAt
        updatedAt
        generalHealthEntrySurveyEntryId
      }
      symptomsEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        createdAt
        symptoms
        medicalConditions
        updatedAt
        symptomEntrySurveyEntryId
      }
      monthlyEntry {
        id
        state
        countyState
        surveyEntry {
          id
          email
          createdAt
          surveyVersion
          surveyType
          age
          race
          timeElapsed
          updatedAt
          surveyEntryCovidEntryId
          surveyEntryVaccinationEntryId
          surveyEntrySocialDeterminantsEntryId
          surveyEntryRecoveryEntryId
          surveyEntryGeneralHealthEntryId
          surveyEntrySymptomsEntryId
          surveyEntryMonthlyEntryId
        }
        age
        race
        results
        createdAt
        updatedAt
        monthlyEntrySurveyEntryId
      }
      updatedAt
      surveyEntryCovidEntryId
      surveyEntryVaccinationEntryId
      surveyEntrySocialDeterminantsEntryId
      surveyEntryRecoveryEntryId
      surveyEntryGeneralHealthEntryId
      surveyEntrySymptomsEntryId
      surveyEntryMonthlyEntryId
    }
  }
`;
export const onCreateVaccinationEntry = /* GraphQL */ `
  subscription OnCreateVaccinationEntry {
    onCreateVaccinationEntry {
      id
      state
      countyState
      age
      race
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      totalVaccineShots
      vaccinated
      vaccineType
      dateOfLastVaccine
      createdAt
      updatedAt
      vaccinationEntrySurveyEntryId
    }
  }
`;
export const onUpdateVaccinationEntry = /* GraphQL */ `
  subscription OnUpdateVaccinationEntry {
    onUpdateVaccinationEntry {
      id
      state
      countyState
      age
      race
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      totalVaccineShots
      vaccinated
      vaccineType
      dateOfLastVaccine
      createdAt
      updatedAt
      vaccinationEntrySurveyEntryId
    }
  }
`;
export const onDeleteVaccinationEntry = /* GraphQL */ `
  subscription OnDeleteVaccinationEntry {
    onDeleteVaccinationEntry {
      id
      state
      countyState
      age
      race
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      totalVaccineShots
      vaccinated
      vaccineType
      dateOfLastVaccine
      createdAt
      updatedAt
      vaccinationEntrySurveyEntryId
    }
  }
`;
export const onCreateCovidEntry = /* GraphQL */ `
  subscription OnCreateCovidEntry {
    onCreateCovidEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      timesPositive
      lastPositive
      tested
      testMethod
      hospitalized
      symptomatic
      symptomsPreventScale
      medicationsTaken
      returnedToHealth
      createdAt
      updatedAt
      covidEntrySurveyEntryId
    }
  }
`;
export const onUpdateCovidEntry = /* GraphQL */ `
  subscription OnUpdateCovidEntry {
    onUpdateCovidEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      timesPositive
      lastPositive
      tested
      testMethod
      hospitalized
      symptomatic
      symptomsPreventScale
      medicationsTaken
      returnedToHealth
      createdAt
      updatedAt
      covidEntrySurveyEntryId
    }
  }
`;
export const onDeleteCovidEntry = /* GraphQL */ `
  subscription OnDeleteCovidEntry {
    onDeleteCovidEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      timesPositive
      lastPositive
      tested
      testMethod
      hospitalized
      symptomatic
      symptomsPreventScale
      medicationsTaken
      returnedToHealth
      createdAt
      updatedAt
      covidEntrySurveyEntryId
    }
  }
`;
export const onCreateRecoveryEntry = /* GraphQL */ `
  subscription OnCreateRecoveryEntry {
    onCreateRecoveryEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      recovered
      lengthOfRecovery {
        months
        days
      }
      hasLongCovid
      createdAt
      updatedAt
      recoveryEntrySurveyEntryId
    }
  }
`;
export const onUpdateRecoveryEntry = /* GraphQL */ `
  subscription OnUpdateRecoveryEntry {
    onUpdateRecoveryEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      recovered
      lengthOfRecovery {
        months
        days
      }
      hasLongCovid
      createdAt
      updatedAt
      recoveryEntrySurveyEntryId
    }
  }
`;
export const onDeleteRecoveryEntry = /* GraphQL */ `
  subscription OnDeleteRecoveryEntry {
    onDeleteRecoveryEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      recovered
      lengthOfRecovery {
        months
        days
      }
      hasLongCovid
      createdAt
      updatedAt
      recoveryEntrySurveyEntryId
    }
  }
`;
export const onCreateGeneralHealthEntry = /* GraphQL */ `
  subscription OnCreateGeneralHealthEntry {
    onCreateGeneralHealthEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      health
      generalHealthResults
      totalScore
      createdAt
      updatedAt
      generalHealthEntrySurveyEntryId
    }
  }
`;
export const onUpdateGeneralHealthEntry = /* GraphQL */ `
  subscription OnUpdateGeneralHealthEntry {
    onUpdateGeneralHealthEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      health
      generalHealthResults
      totalScore
      createdAt
      updatedAt
      generalHealthEntrySurveyEntryId
    }
  }
`;
export const onDeleteGeneralHealthEntry = /* GraphQL */ `
  subscription OnDeleteGeneralHealthEntry {
    onDeleteGeneralHealthEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      health
      generalHealthResults
      totalScore
      createdAt
      updatedAt
      generalHealthEntrySurveyEntryId
    }
  }
`;
export const onCreateSymptomEntry = /* GraphQL */ `
  subscription OnCreateSymptomEntry {
    onCreateSymptomEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      createdAt
      symptoms
      medicalConditions
      updatedAt
      symptomEntrySurveyEntryId
    }
  }
`;
export const onUpdateSymptomEntry = /* GraphQL */ `
  subscription OnUpdateSymptomEntry {
    onUpdateSymptomEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      createdAt
      symptoms
      medicalConditions
      updatedAt
      symptomEntrySurveyEntryId
    }
  }
`;
export const onDeleteSymptomEntry = /* GraphQL */ `
  subscription OnDeleteSymptomEntry {
    onDeleteSymptomEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      createdAt
      symptoms
      medicalConditions
      updatedAt
      symptomEntrySurveyEntryId
    }
  }
`;
export const onCreateSocialDeterminantsEntry = /* GraphQL */ `
  subscription OnCreateSocialDeterminantsEntry {
    onCreateSocialDeterminantsEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      hasMedicalInsurance
      difficultCoveringExpenses
      currentWorkSituation
      createdAt
      updatedAt
      socialDeterminantsEntrySurveyEntryId
    }
  }
`;
export const onUpdateSocialDeterminantsEntry = /* GraphQL */ `
  subscription OnUpdateSocialDeterminantsEntry {
    onUpdateSocialDeterminantsEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      hasMedicalInsurance
      difficultCoveringExpenses
      currentWorkSituation
      createdAt
      updatedAt
      socialDeterminantsEntrySurveyEntryId
    }
  }
`;
export const onDeleteSocialDeterminantsEntry = /* GraphQL */ `
  subscription OnDeleteSocialDeterminantsEntry {
    onDeleteSocialDeterminantsEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      hasMedicalInsurance
      difficultCoveringExpenses
      currentWorkSituation
      createdAt
      updatedAt
      socialDeterminantsEntrySurveyEntryId
    }
  }
`;
export const onCreateMonthlyEntry = /* GraphQL */ `
  subscription OnCreateMonthlyEntry {
    onCreateMonthlyEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      results
      createdAt
      updatedAt
      monthlyEntrySurveyEntryId
    }
  }
`;
export const onUpdateMonthlyEntry = /* GraphQL */ `
  subscription OnUpdateMonthlyEntry {
    onUpdateMonthlyEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      results
      createdAt
      updatedAt
      monthlyEntrySurveyEntryId
    }
  }
`;
export const onDeleteMonthlyEntry = /* GraphQL */ `
  subscription OnDeleteMonthlyEntry {
    onDeleteMonthlyEntry {
      id
      state
      countyState
      surveyEntry {
        id
        email
        createdAt
        surveyVersion
        surveyType
        age
        race
        timeElapsed
        covidEntry {
          id
          state
          countyState
          age
          race
          timesPositive
          lastPositive
          tested
          testMethod
          hospitalized
          symptomatic
          symptomsPreventScale
          medicationsTaken
          returnedToHealth
          createdAt
          updatedAt
          covidEntrySurveyEntryId
        }
        vaccinationEntry {
          id
          state
          countyState
          age
          race
          totalVaccineShots
          vaccinated
          vaccineType
          dateOfLastVaccine
          createdAt
          updatedAt
          vaccinationEntrySurveyEntryId
        }
        socialDeterminantsEntry {
          id
          state
          countyState
          age
          race
          hasMedicalInsurance
          difficultCoveringExpenses
          currentWorkSituation
          createdAt
          updatedAt
          socialDeterminantsEntrySurveyEntryId
        }
        recoveryEntry {
          id
          state
          countyState
          age
          race
          recovered
          hasLongCovid
          createdAt
          updatedAt
          recoveryEntrySurveyEntryId
        }
        generalHealthEntry {
          id
          state
          countyState
          age
          race
          health
          generalHealthResults
          totalScore
          createdAt
          updatedAt
          generalHealthEntrySurveyEntryId
        }
        symptomsEntry {
          id
          state
          countyState
          age
          race
          createdAt
          symptoms
          medicalConditions
          updatedAt
          symptomEntrySurveyEntryId
        }
        monthlyEntry {
          id
          state
          countyState
          age
          race
          results
          createdAt
          updatedAt
          monthlyEntrySurveyEntryId
        }
        updatedAt
        surveyEntryCovidEntryId
        surveyEntryVaccinationEntryId
        surveyEntrySocialDeterminantsEntryId
        surveyEntryRecoveryEntryId
        surveyEntryGeneralHealthEntryId
        surveyEntrySymptomsEntryId
        surveyEntryMonthlyEntryId
      }
      age
      race
      results
      createdAt
      updatedAt
      monthlyEntrySurveyEntryId
    }
  }
`;
