"symptoms": {
  "Weakness or fatigue": "No",
  "Feeling sick after you exert yourself physically or mentally": "No",
  "Fever, chills, sweats or flushing": "No",
  "Loss of or change in smell or taste": "No",
  "Headache": "No",
  "Body or muscle aches": "No",
  "Shortness of breath (trouble breathing)": "No",
  "Cough": "No",
  "Palpitations or racing heart beat": "No",
  "Swelling of your legs": "No",
  "Nausea": "No",
  "Vomiting": "No",
  "Diarrhea": "No",
  "Constipation": "No",
  "Bladder problems including incontinence, trouble passing urine or emptying bladder": "No",
  "Nerve problems including tremor, shaking, numbness, tingling, or burning sensation": "No",
  "Anxiety, depression, or stress": "No",
  "Problems thinking or concentrating": "No",
  "Trouble sleeping": "No",
  "Feeling faint, lightheaded or dizzy after standing up": "No",
  "Skin color changes or rash": "No",
  "Excessively dry mouth or excessive thirst": "No",
  "Vision problems": "No",
  "Problems with hearing (hearing loss, ringing in ears)": "No",
  "Hair loss": "No",
  "Problems with teeth": "No",
  "Changes to menstrual cycle or menopause symptoms (such as hot flashes)": "No",
  "Changes in desire for, comfort with or capacity for sex": "No"
},
"